"""empty message

Revision ID: 39f997838a68
Revises: 27ac73d40e12
Create Date: 2022-09-15 12:29:57.971549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39f997838a68'
down_revision = '27ac73d40e12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('product_id', table_name='product_user')
    op.drop_index('user_id', table_name='product_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('user_id', 'product_user', ['user_id'], unique=False)
    op.create_index('product_id', 'product_user', ['product_id'], unique=False)
    # ### end Alembic commands ###
