"""empty message

Revision ID: eb8e1fa948e0
Revises: 2b67ac85c34a
Create Date: 2022-09-15 12:02:41.448780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb8e1fa948e0'
down_revision = '2b67ac85c34a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'product_user', ['product_id'])
    op.create_unique_constraint(None, 'product_user', ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_user', type_='unique')
    op.drop_constraint(None, 'product_user', type_='unique')
    # ### end Alembic commands ###
